OkulBilisim\LocationBundle\Entity\Country:
  type: entity
  table: country
  repositoryClass: OkulBilisim\LocationBundle\Entity\CountryRepository
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    provinces:
      targetEntity: OkulBilisim\LocationBundle\Entity\Province
      mappedBy: country
      fetch: EXTRA_LAZY
